import React, { useEffect, useMemo, useState } from "react";
import { Alert, FlatList, Linking, Modal, Pressable, Text, TextInput, View } from "react-native";
import * as Contacts from "expo-contacts";
import { useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";

export default function ContactsScreen() {
  const router = useRouter(); const [items, setItems] = useState<Contacts.Contact[]>([]); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [editing, setEditing] = useState<Contacts.Contact | null>(null); const [modalVisible, setModalVisible] = useState(false); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [email, setEmail] = useState("");
  async function load() { const p = await Contacts.requestPermissionsAsync(); if (p.status !== "granted") { setError("Contacts permission was denied."); return; } const r = await Contacts.getContactsAsync({ fields: [Contacts.Fields.Emails, Contacts.Fields.PhoneNumbers, Contacts.Fields.Image] }); setItems(r.data); }
  useEffect(() => { load().catch(() => setError("Unable to load contacts.")); }, []);
  const filtered = useMemo(() => items.filter(x => (x.name + " " + x.emails?.[0]?.email).toLowerCase().includes(query.toLowerCase())), [items, query]);
  function openEditor(contact?: Contacts.Contact) { setEditing(contact || null); setName(contact?.name || ""); setPhone(contact?.phoneNumbers?.[0]?.number || ""); setEmail(contact?.emails?.[0]?.email || ""); setModalVisible(true); }
  async function save() { if (!name.trim()) return Alert.alert("Name required"); const data: any = { contactType: Contacts.ContactTypes.Person, name: name.trim(), phoneNumbers: phone ? [{ label: "mobile", number: phone }] : [], emails: email ? [{ label: "home", email }] : [] }; try { if ((editing as any)?.id) await Contacts.updateContactAsync({ ...editing, ...data } as any); else await Contacts.addContactAsync(data); setEditing(null); setModalVisible(false); await load(); } catch { Alert.alert("Could not save contact"); } }
  function remove() { const id = (editing as any)?.id; if (!id) return; Alert.alert("Delete contact?", "This cannot be undone.", [{ text: "Cancel" }, { text: "Delete", style: "destructive", onPress: async () => { await Contacts.removeContactAsync(id); setEditing(null); setModalVisible(false); load(); } }]); }
  function link(contact: Contacts.Contact) { const number = contact.phoneNumbers?.[0]?.number; const mail = contact.emails?.[0]?.email; if (number) Linking.openURL("tel:" + number); else if (mail) Linking.openURL("mailto:" + mail); else Alert.alert("No link", "This contact has no phone or email."); }
  return <SafeAreaView style={styles.page}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><View style={styles.heading}><Text style={styles.title}>Contacts</Text><Pressable onPress={() => openEditor()}><Text style={styles.add}>+ Add</Text></Pressable></View><TextInput placeholder="Search contacts" value={query} onChangeText={setQuery} style={styles.search} />{error ? <Text style={styles.error}>{error}</Text> : <FlatList data={filtered} keyExtractor={(x, i) => (x.name || "contact") + i} renderItem={({ item }) => <Pressable onPress={() => openEditor(item)} onLongPress={() => link(item)} style={styles.item}><View><Text style={styles.name}>{item.name}</Text><Text style={styles.detail}>{item.phoneNumbers?.[0]?.number || item.emails?.[0]?.email || "No contact details"}</Text></View><Text style={styles.link}>Open</Text></Pressable>} ListEmptyComponent={<Text style={styles.detail}>No contacts found.</Text>} />}<Modal visible={modalVisible} transparent animationType="slide"><View style={styles.modal}><Text style={styles.title}>{editing ? "Edit contact" : "Add contact"}</Text><TextInput placeholder="Name" value={name} onChangeText={setName} style={styles.search} /><TextInput placeholder="Phone" value={phone} onChangeText={setPhone} keyboardType="phone-pad" style={styles.search} /><TextInput placeholder="Email" value={email} onChangeText={setEmail} keyboardType="email-address" style={styles.search} /><View style={{ flexDirection: "row", justifyContent: "center" }}><Pressable onPress={() => setModalVisible(false)} style={styles.cancel}><Text>Cancel</Text></Pressable><Pressable onPress={save} style={styles.save}><Text style={{ color: "#fff", fontWeight: "800" }}>Save</Text></Pressable>{editing ? <Pressable onPress={remove} style={styles.delete}><Text style={{ color: "#fff" }}>Delete</Text></Pressable> : null}</View></View></Modal></SafeAreaView>;
}
const styles: any = { page: { flex: 1, padding: 20, backgroundColor: "#F7F8F5" }, back: { color: "#175C54", fontWeight: "800", marginBottom: 18 }, heading: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, title: { fontSize: 28, fontWeight: "800" }, add: { color: "#175C54", fontWeight: "800" }, search: { backgroundColor: "#fff", borderRadius: 14, padding: 15, marginVertical: 12 }, item: { paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: "#dde5df", flexDirection: "row", justifyContent: "space-between" }, name: { fontWeight: "800", fontSize: 16 }, detail: { color: "#6d7d75", marginTop: 4 }, link: { color: "#175C54", fontWeight: "800" }, error: { color: "#C85C53", padding: 20 }, modal: { marginTop: "auto", backgroundColor: "#fff", padding: 24, borderTopLeftRadius: 24, borderTopRightRadius: 24 }, cancel: { padding: 15, margin: 4 }, save: { padding: 15, margin: 4, borderRadius: 12, backgroundColor: "#175C54" }, delete: { padding: 15, margin: 4, borderRadius: 12, backgroundColor: "#C85C53" } };
