import React, { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Image, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import * as ImagePicker from "expo-image-picker";
import * as ImageManipulator from "expo-image-manipulator";
import { useLocalSearchParams, useRouter } from "expo-router";
import { colleges, College } from "../../src/data";
import { apiRequest, fetchCollege, uploadMedia } from "../../src/api";
import { useAuth } from "../../src/auth";
import { Pill, SectionTitle, s } from "../../src/components";

export default function CollegeDetails() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const { token } = useAuth();
  const [college, setCollege] = useState<College | null>(colleges.find(x => x.id === id) || colleges[0]);
  const [media, setMedia] = useState<any[]>([]); const [reviews, setReviews] = useState<any[]>([]); const [review, setReview] = useState({ rating: "5", title: "", comment: "" }); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!id) return; Promise.all([fetchCollege(id).then(setCollege).catch(() => {}), apiRequest<{items:any[]}>("/media/" + id).then(x => setMedia(x.items)).catch(() => {}), apiRequest<{items:any[]}>("/reviews/" + id).then(x => setReviews(x.items)).catch(() => {})]); }, [id]);
  async function chooseImage() { if (!token || !college?.backendId) { Alert.alert("Sign in required", "You need an account to upload campus media."); return; } const p = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!p.granted) { Alert.alert("Permission denied", "Gallery permission is required."); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], quality: 0.8 }); if (result.canceled) return; setBusy(true); try { const compressed = await ImageManipulator.manipulateAsync(result.assets[0].uri, [{ resize: { width: 1400 } }], { compress: 0.75, format: ImageManipulator.SaveFormat.JPEG }); await uploadMedia(compressed.uri, college.backendId, token, college.name + " campus photo"); Alert.alert("Uploaded", "Your image is pending moderation."); } catch (e) { Alert.alert("Upload failed", e instanceof Error ? e.message : "Please try again."); } finally { setBusy(false); } }
  async function submitReview() { if (!token || !college?.backendId || !review.title.trim() || !review.comment.trim()) { Alert.alert("Complete the form", "Add a title and comment before submitting."); return; } setBusy(true); try { await apiRequest("/reviews", { method: "POST", token, body: { collegeId: college.backendId, ...review, rating: Number(review.rating) } }); setReview({ rating: "5", title: "", comment: "" }); Alert.alert("Submitted", "Your review is pending moderation."); } catch (e) { Alert.alert("Review failed", e instanceof Error ? e.message : "Please try again."); } finally { setBusy(false); } }
  if (!college) return <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}><Text>College not found</Text></View>;
  return <View style={{ flex: 1, backgroundColor: "#F7F8F5" }}><ScrollView><View><Image source={{ uri: college.image }} style={{ width: "100%", height: 300 }} /><SafeAreaView style={{ position: "absolute", top: 0, left: 0, right: 0 }}><Pressable onPress={() => router.back()} style={s.back}><Text>‹ Back</Text></Pressable></SafeAreaView></View><View style={{ marginTop: -25, borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: "#F7F8F5", padding: 22 }}><Text style={{ color: "#2C8A65", fontSize: 12, fontWeight: "800" }}>✓ VERIFIED INSTITUTION</Text><Text style={{ color: "#162522", fontSize: 28, fontWeight: "800", marginTop: 8 }}>{college.name}</Text><Text style={{ color: "#71807B", fontSize: 13, marginTop: 8 }}>{college.city}, {college.state} · {college.type}</Text><View style={{ flexDirection: "row", gap: 10, marginVertical: 20 }}><View style={s.detailChip}><Text style={{ fontWeight: "800" }}>★ {college.rating} rating</Text></View><View style={s.detailChip}><Text style={{ fontWeight: "800" }}>⌖ {college.distance} away</Text></View></View><SectionTitle title="About" /><Text style={{ color: "#71807B", fontSize: 14, lineHeight: 22, marginBottom: 24 }}>{college.description}</Text><SectionTitle title="Popular courses" /><View style={{ flexDirection: "row", gap: 8, marginBottom: 26 }}>{college.courses.map(x => <Pill key={x} label={x} />)}</View><SectionTitle title="Campus media" link="Add image" /><Pressable onPress={chooseImage} style={s.save}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={{ color: "#fff", fontWeight: "800" }}>Pick, compress and upload image</Text>}</Pressable>{media.map(item => <Image key={item._id} source={{ uri: item.url }} style={{ width: "100%", height: 180, borderRadius: 16, marginBottom: 10 }} />)}<SectionTitle title="Reviews" /><TextInput placeholder="Review title" value={review.title} onChangeText={title => setReview({ ...review, title })} style={styles.input} /><TextInput placeholder="Share your experience" multiline value={review.comment} onChangeText={comment => setReview({ ...review, comment })} style={[styles.input, { height: 90 }]} /><Pressable onPress={submitReview} style={s.save}><Text style={{ color: "#fff", fontWeight: "800" }}>Submit review</Text></Pressable>{reviews.map(item => <View key={item._id} style={styles.review}><Text style={{ fontWeight: "800" }}>{item.title} · {item.rating}/5</Text><Text style={{ color: "#71807B", marginTop: 5 }}>{item.comment}</Text></View>)}</View></ScrollView></View>;
}
const styles: any = { input: { backgroundColor: "#fff", borderRadius: 12, padding: 14, marginBottom: 10, textAlignVertical: "top" }, review: { backgroundColor: "#fff", borderRadius: 12, padding: 14, marginBottom: 10 } };
